#!/usr/bin/env python3
# Copyright 2026 Arm Limited and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
"""Convert the example CNN into an Ethos-U85 .pte and a C header for the build.

This is the "model conversion" build step. It is driven by the MLOps metadata
that CMSIS-Toolbox generates from the `mlops:` node of the csolution: the
`*.cbuild-mlops.yml` file. The NPU accelerator, Vela system-config and
memory-mode are read from there instead of being hard-coded, so a data
scientist can retarget the NPU purely by editing the csolution.

  https://open-cmsis-pack.github.io/cmsis-toolbox/build-overview/#mlops-information

Usage (as run by the cproject `executes:` step):
  python export_model.py --mlops ../cmsis-executorch-simple.cbuild-mlops.yml \
      --output-dir . --header ../ai_layer/model/model_pte.h
"""

import argparse
import binascii
import re
import sys
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).resolve().parent))
from model import get_example_inputs, get_model  # noqa: E402


def _load_mlops(path: Path) -> dict:
    """Extract the Vela knobs from a *.cbuild-mlops.yml.

    Returns target / system_config / memory_mode / config_ini. Falls back to
    Ethos-U85 defaults when a field (or the whole file) is absent, so a first
    build before `cbuild --active` has generated the file still works.
    """
    target = system_config = memory_mode = config_ini = None
    macs = None
    if path and path.is_file():
        text = path.read_text()
        opts = re.search(r"options:\s*(.+)", text)
        if opts:
            line = opts.group(1)
            m = re.search(r"--accelerator-config[= ]([^\s]+)", line)
            target = m.group(1) if m else target
            m = re.search(r"--system-config[= ]([^\s]+)", line)
            system_config = m.group(1) if m else system_config
            m = re.search(r"--memory-mode[= ]([^\s]+)", line)
            memory_mode = m.group(1) if m else memory_mode
        m = re.search(r"ini:\s*(\S+)", text)
        if m:
            config_ini = m.group(1)
        m = re.search(r"macs:\s*(\d+)", text)
        if m:
            macs = m.group(1)

    if target is None:
        target = f"ethos-u85-{macs}" if macs else "ethos-u85-256"
    return {
        "target": target,
        "system_config": system_config,
        "memory_mode": memory_mode,
        "config_ini": config_ini,
    }


def _strip_guards_fn(gm) -> None:
    """Drop the dead `_guards_fn` call_module torch 2.12 export emits, which
    older Arm annotation passes iterate over unconditionally."""
    changed = False
    for node in list(gm.graph.nodes):
        if node.op == "call_module" and str(node.target) == "_guards_fn":
            gm.graph.erase_node(node)
            changed = True
    if changed:
        gm.graph.eliminate_dead_code()
        gm.recompile()


def _write_header(pte_path: Path, header_path: Path, symbol: str) -> None:
    data = pte_path.read_bytes()
    header_path.parent.mkdir(parents=True, exist_ok=True)
    hexstream = binascii.hexlify(data).decode()
    lines = [
        "// Generated by model/export_model.py -- do not edit.",
        f"__attribute__((aligned(16))) const unsigned char {symbol}[] = {{",
    ]
    body = []
    for i in range(0, len(hexstream), 2):
        if i % 64 == 0:
            body.append("\n  ")
        body.append("0x" + hexstream[i : i + 2] + ", ")
    lines.append("".join(body))
    lines.append("};")
    lines.append(f"const unsigned long {symbol}_size = sizeof({symbol});")
    header_path.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--mlops",
        type=Path,
        help="Path to the CMSIS-Toolbox generated *.cbuild-mlops.yml",
    )
    parser.add_argument("--output-dir", type=Path, default=Path("."))
    parser.add_argument(
        "--header",
        type=Path,
        default=Path("../ai_layer/model/model_pte.h"),
        help="C header emitted for the firmware to embed the .pte",
    )
    parser.add_argument("--symbol", default="model_pte")
    args = parser.parse_args()

    cfg = _load_mlops(args.mlops)
    print(
        f"[export] target={cfg['target']} system_config={cfg['system_config']} "
        f"memory_mode={cfg['memory_mode']} config_ini={cfg['config_ini']}"
    )

    from executorch.backends.arm.ethosu import EthosUCompileSpec, EthosUPartitioner
    from executorch.backends.arm.quantizer import (
        EthosUQuantizer,
        get_symmetric_quantization_config,
    )
    from executorch.exir import (
        EdgeCompileConfig,
        ExecutorchBackendConfig,
        to_edge_transform_and_lower,
    )
    from executorch.extension.export_util.utils import save_pte_program
    from torchao.quantization.pt2e.quantize_pt2e import convert_pt2e, prepare_pt2e

    compile_spec_kwargs = {"target": cfg["target"]}
    if cfg["system_config"]:
        compile_spec_kwargs["system_config"] = cfg["system_config"]
    if cfg["memory_mode"]:
        compile_spec_kwargs["memory_mode"] = cfg["memory_mode"]
    if cfg["config_ini"] and Path(cfg["config_ini"]).is_file():
        compile_spec_kwargs["config_ini"] = cfg["config_ini"]
    compile_spec = EthosUCompileSpec(**compile_spec_kwargs)

    model = get_model()
    example_inputs = get_example_inputs()

    exported = torch.export.export(model, example_inputs)
    _strip_guards_fn(exported.graph_module)
    graph_module = exported.module()
    _strip_guards_fn(graph_module)

    # Quantize the whole graph (set_global) so the partitioner can move every
    # node into the Ethos-U delegate, leaving only a float<->int8 boundary.
    quantizer = EthosUQuantizer(compile_spec)
    quantizer.set_global(get_symmetric_quantization_config(is_per_channel=True))
    prepared = prepare_pt2e(graph_module, quantizer)
    prepared(*example_inputs)  # calibrate
    quantized = convert_pt2e(prepared)

    quantized_exported = torch.export.export(quantized, example_inputs)
    _strip_guards_fn(quantized_exported.graph_module)

    # The whole graph is delegated to the Ethos-U; only a float<->int8 boundary
    # quantize/dequantize stays on the CPU, served by the portable Quantized
    # kernels (see the AI layer). Keeping it on quantized_decomposed avoids a
    # dependency on the Cortex-M AOT backend for this fully-delegated example.
    edge = to_edge_transform_and_lower(
        quantized_exported,
        partitioner=[EthosUPartitioner(compile_spec)],
        compile_config=EdgeCompileConfig(_check_ir_validity=False),
    )

    program = edge.to_executorch(
        config=ExecutorchBackendConfig(extract_delegate_segments=False)
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    pte_path = args.output_dir / "model.pte"
    save_pte_program(program, str(pte_path))
    print(f"[export] wrote {pte_path} ({pte_path.stat().st_size} bytes)")

    _write_header(pte_path, args.header, args.symbol)
    print(f"[export] wrote {args.header}")


if __name__ == "__main__":
    main()
