/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0
 *
 * Project: 'executorch_project.Debug+AVH-SSE-300' 
 * Target:  'Debug+AVH-SSE-300' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE300MPS3.h"

/* ARM::Device:Native Driver:SysCounter@1.1.0 */
#define RTE_SYSCOUNTER      1
/* ARM::Device:Native Driver:Timeout@1.0.0 */
#define RTE_TIMEOUT      1
/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.25.2 */
#define RTE_ETHOS_U_CORE_DRIVER


#endif /* RTE_COMPONENTS_H */
