/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0
 *
 * Project: 'executorch_project.Release+AVH-SSE-300' 
 * Target:  'Release+AVH-SSE-300' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.25.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55


#endif /* PRE_INCLUDE_GLOBAL_H */
