/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p18-g2c6f0d5f
 *
 * Project: 'executorch_project.Debug+DevKit-E7-HE' 
 * Target:  'Debug+DevKit-E7-HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.25.2 */
#define RTE_ETHOS_U_CORE_DRIVER
/* AlifSemiconductor::BSP:External peripherals:Ethernet PHY@2.0.0 */
#define RTE_Drivers_PHY_GENERIC           /* Driver PHY generic */
/* AlifSemiconductor::CMSIS Driver:Ethernet MAC@2.0.0 */
#define RTE_Drivers_ETH_MAC           /* Driver ETH MAC */
/* AlifSemiconductor::CMSIS Driver:GPIO@1.0.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::CMSIS Driver:I2C@2.0.0 */
#define RTE_Drivers_I2C              /* Driver I2C */
/* AlifSemiconductor::CMSIS Driver:SAI@2.0.0 */
#define RTE_Drivers_SAI              /* Driver SAI */
/* AlifSemiconductor::CMSIS Driver:SPI@2.0.0 */
#define RTE_Drivers_SPI              /* Driver SPI */
/* AlifSemiconductor::CMSIS Driver:USART@2.0.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::CMSIS Driver:VIO:Board&DevKit-E7@1.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_DEVKIT_E7
/* AlifSemiconductor::CMSIS Driver:vStream:AudioIn&DevKit-E7@1.0.0 */
#define RTE_VSTREAM_AUDIOIN
#define RTE_VSTREAM_AUDIOIN_DEVKIT_E7
/* AlifSemiconductor::Device:SOC Peripherals:DMA@2.0.0 */
#define RTE_Drivers_DMA                   /* Driver DMA*/
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.0.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
