#!/usr/bin/env bash
# Start fvp-gdb (GDB-RSP front-end for Arm FVPs via Iris) unless one is already
# listening. fvp-gdb is started detached (FVP/UART output goes to a log file)
# so this script EXITS once the port is up: a still-running preLaunchTask
# would not be re-executed by VS Code on the next debug start, and the
# --reload path would never run again (debug would only ever work once).
# The "ready on :<port>" / "already listening" lines are the problemMatcher
# endsPattern that unblocks the debug launch — keep the echo strings in sync
# with tasks.json. Generated by the fvp-debug-setup skill.
set -euo pipefail

# --reload: stop any running instance first, so the FVP boots the current ELF
# (used by the "CMSIS Load" task override — load semantics = fresh image).
RELOAD=0
if [[ "${1:-}" == "--reload" ]]; then
    RELOAD=1
    shift
fi

# $1 = application ELF, delivered by the CMSIS csolution extension
# (${command:cmsis-csolution.getBinaryFile}) via the task args.
ELF="${1:?usage: start-fvp-gdb.sh [--reload] <application.elf>}"
[[ -f "${ELF}" ]] || { echo "ELF not found: ${ELF} (build the active context first)"; exit 1; }

GDB_PORT="${FVP_GDB_PORT:-3333}"
FVP_CMD="${FVP_BIN:-FVP_Corstone_SSE-320}"
FVP_ARGS=(-f board/Corstone-320/fvp_config.txt)

listening() {
    lsof -nP -iTCP:"${GDB_PORT}" -sTCP:LISTEN >/dev/null 2>&1
}

if listening; then
    if [[ "${RELOAD}" == "1" ]]; then
        echo "Reload requested: stopping running fvp-gdb instance"
        "$(dirname "$0")/stop-fvp-gdb.sh"
        for _ in $(seq 1 15); do listening || break; sleep 1; done
    else
        echo "fvp-gdb already listening on :${GDB_PORT}"
        exit 0
    fi
fi

command -v fvp-gdb >/dev/null 2>&1 || {
    echo "fvp-gdb not found on PATH. Install with:"
    echo "  python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple fvp-gdb"
    exit 1
}
command -v "${FVP_CMD}" >/dev/null 2>&1 || {
    echo "${FVP_CMD} not found on PATH (set FVP_BIN or install the Corstone-320 FVP)"
    exit 1
}

EXTRA=()
if [[ "$(uname)" == "Darwin" ]]; then
    # The FVPs-on-Mac wrapper runs the FVP in docker and only publishes port
    # 7100, so pin the Iris port fvp-gdb injects to it.
    EXTRA+=(--iris-port 7100)
    docker info >/dev/null 2>&1 || {
        echo "Docker is not running (the FVP runs in a container on macOS)"
        exit 1
    }
fi

# WARNING log level keeps fvp-gdb's per-packet GDB traffic out of the log
# so the firmware's UART/semihosting output stays readable.
LOG="${FVP_GDB_LOG:-${TMPDIR:-/tmp}/fvp-gdb.log}"
echo "Starting fvp-gdb --launch ${FVP_CMD} -a ${ELF} ..."
nohup fvp-gdb --log-level WARNING "${EXTRA[@]}" --gdb-port "${GDB_PORT}" \
    --launch "${FVP_CMD}" "${FVP_ARGS[@]}" -a "${ELF}" >"${LOG}" 2>&1 &
FVP_GDB_PID=$!
disown "${FVP_GDB_PID}"

# First macOS run may build the fvp docker image; be generous.
for _ in $(seq 1 120); do
    listening && break
    kill -0 "${FVP_GDB_PID}" 2>/dev/null || { echo "fvp-gdb exited before serving :${GDB_PORT} (see ${LOG})"; exit 1; }
    sleep 1
done
listening || { echo "fvp-gdb did not come up within 120s"; kill "${FVP_GDB_PID}" 2>/dev/null || true; exit 1; }

echo "fvp-gdb ready on :${GDB_PORT} — FVP/UART output: tail -f ${LOG}"
