#!/usr/bin/env bash
# Stop fvp-gdb and its FVP subprocess (plus the docker container on macOS).
# Generated by the fvp-debug-setup skill.
set -uo pipefail

# Match "bin/fvp-gdb" (the installed executable), NOT plain "fvp-gdb": the
# task shell running start-fvp-gdb.sh has the script path on its command line,
# and Linux pkill -f, unlike BSD/macOS, does not spare its own ancestors — a
# broader pattern kills the very shell driving the reload.
pkill -f 'bin/fvp-gdb' && echo "fvp-gdb stopped" || echo "no fvp-gdb instance running"

# The FVP itself is a separate process: fvp-gdb --launch spawns it, and pkill
# above only matches fvp-gdb. Kill orphaned FVPs too (on macOS this hits the
# FVPs-on-Mac wrapper; the container is handled below).
pkill -f 'bin/FVP_Corstone' && echo "FVP process(es) stopped" || true

if [[ "$(uname)" == "Darwin" ]] && docker info >/dev/null 2>&1; then
    ids="$(docker ps --format '{{.ID}} {{.Image}}' | awk '$2 ~ /^fvp:/ {print $1}')"
    if [[ -n "${ids}" ]]; then
        echo "${ids}" | xargs docker kill >/dev/null 2>&1 && echo "FVP container(s) killed"
    fi
fi
exit 0
