#!/usr/bin/env bash
# Stream the detached fvp-gdb/FVP log into a VS Code task terminal. fvp-gdb
# runs detached (see start-fvp-gdb.sh) so the Load task can exit and be re-run
# on every debug start; this companion task makes the FVP/semihosting output
# visible live anyway. tail -F follows across the truncation each reload does.
# The "ready" echo is the problemMatcher endsPattern — keep in sync with
# tasks.json. Generated by the fvp-debug-setup skill.
set -uo pipefail

LOG="${FVP_GDB_LOG:-${TMPDIR:-/tmp}/fvp-gdb.log}"
touch "${LOG}" 2>/dev/null || true
echo "FVP output terminal ready — streaming ${LOG}"
exec tail -n +1 -F "${LOG}"
