/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0
 *
 * Project: 'executorch_project.Debug+AVH-SSE-320' 
 * Target:  'Debug+AVH-SSE-320' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U85@1.25.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u85


#endif /* PRE_INCLUDE_GLOBAL_H */
