/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.15.1+p3-gf46d68bf
 *
 * Project: 'cmsis-executorch.Debug+DevKit-E8' 
 * Target:  'Debug+DevKit-E8' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U85@1.26.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u85
/* PyTorch::Machine Learning:ExecuTorch:Backend EthosU@1.5.1 */
#define EXECUTORCH_BUILD_ARM_BAREMETAL 1
        #define ET_USE_ETHOS_U_BACKEND 1
/* PyTorch::Machine Learning:ExecuTorch:Runtime@1.5.1 */
/* ExecuTorch global configuration */
        #define C10_USING_CUSTOM_GENERATED_MACROS
        #define FLATBUFFERS_MAX_ALIGNMENT 1024
        #define FLATBUFFERS_LOCALE_INDEPENDENT 0


#endif /* PRE_INCLUDE_GLOBAL_H */
