/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p88-g94cb0c5e
 *
 * Project: 'cmsis-executorch.Debug+DevKit-E8' 
 * Target:  'Debug+DevKit-E8' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U85@1.26.2 */
#define RTE_ETHOS_U_CORE_DRIVER
/* AlifSemiconductor::BSP:External peripherals:ILI9806E LCD panel@2.2.0 */
#define RTE_Drivers_MIPI_DSI_ILI9806E_PANEL    /* Driver ILI9806E LCD panel*/
/* AlifSemiconductor::CMSIS Driver:USART@2.2.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:CDC@2.2.0 */
#define RTE_Drivers_CDC200                 /* Driver CDC200*/
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.2.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI CSI2 DPHY@2.2.0 */
#define RTE_Drivers_MIPI_DSI_CSI2_DPHY   /* Driver DPHY */
/* AlifSemiconductor::Device:SOC Peripherals:MIPI DSI@2.2.0 */
#define RTE_Drivers_MIPI_DSI               /* Driver MIPI DSI */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.2.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */
/* PyTorch::Machine Learning:ExecuTorch Operators:Quantized dequantize@1.5.1 */
#define RTE_ML_EXECUTORCH_OP_QUANTIZED_DEQUANTIZE     /* ExecuTorch op_dequantize */
/* PyTorch::Machine Learning:ExecuTorch Operators:Quantized quantize@1.5.1 */
#define RTE_ML_EXECUTORCH_OP_QUANTIZED_QUANTIZE     /* ExecuTorch op_quantize */
/* PyTorch::Machine Learning:ExecuTorch:Backend EthosU@1.5.1 */
#define RTE_ML_EXECUTORCH_BACKEND_ETHOS_U     /* ExecuTorch Ethos-U Backend (Cortex-M host) */
/* PyTorch::Machine Learning:ExecuTorch:Kernel Registration@1.5.1 */
#define RTE_ML_EXECUTORCH_KERNEL_REGISTRATION     /* ExecuTorch Kernel Registration */
/* PyTorch::Machine Learning:ExecuTorch:Kernel Utils@1.5.1 */
#define RTE_ML_EXECUTORCH_KERNEL_UTILS     /* ExecuTorch Kernel Utils */
/* PyTorch::Machine Learning:ExecuTorch:Runtime@1.5.1 */
#define RTE_ML_EXECUTORCH_RUNTIME     /* ExecuTorch Runtime */


#endif /* RTE_COMPONENTS_H */
