#!/usr/bin/env python3
# Copyright 2026 Arm Limited and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
"""Generate the AI layer's component list from an exported .pte.

The PyTorch::ExecuTorch pack exposes every operator as a selectable CMSIS
component, so an image links only the kernels its model actually uses. This
script reads the operators referenced by a .pte, looks up which components the
pack offers (straight from its .pdsc), and writes an `ai_layer.clayer.yml`
selecting the runtime plus exactly those operator components.

  python scripts/gen_components.py --pte model/model.pte \
      --pack-path packs/PyTorch.ExecuTorch.1.3.1-rc9 \
      --output ai_layer/ai_layer.clayer.yml
"""

import argparse
import re
from pathlib import Path

# quantized_decomposed:: op base name -> "Quantized <Csub>" component suffix.
QUANTIZED_DECOMPOSED_TO_COMPONENT = {
    "quantize_per_tensor": "quantize",
    "quantize_per_channel": "quantize",
    "dequantize_per_tensor": "dequantize",
    "dequantize_per_channel": "dequantize",
    "choose_qparams": "choose_qparams",
    "embedding_byte": "embedding",
}


def pack_component_suffixes(pdsc: Path) -> dict[str, set[str]]:
    """Return the operator Csub suffixes the pack offers, keyed by family
    ('Portable' / 'Quantized' / 'Cortex-M'), parsed from the pack .pdsc."""
    families: dict[str, set[str]] = {"Portable": set(), "Quantized": set(), "Cortex-M": set()}
    for csub in re.findall(r'Csub="([^"]+)"', pdsc.read_text()):
        family, _, name = csub.partition(" ")
        if family == "Cortex-M":
            families["Cortex-M"].add(name)
        elif family in ("Portable", "Quantized"):
            families[family].add(name)
    return families


def extract_ops(pte: Path) -> set[str]:
    """Scan a .pte for aten:: / quantized_decomposed:: / cortex_m:: op names."""
    blob = pte.read_bytes()
    text = blob.decode("latin-1")
    ops: set[str] = set()
    for ns in ("aten", "quantized_decomposed", "cortex_m"):
        ops.update(re.findall(rf"{ns}::\w+(?:\.\w+)*", text))
    return ops


def map_ops(ops: set[str], avail: dict[str, set[str]]) -> tuple[list[str], list[str], list[str], list[str]]:
    portable, quantized, cortex_m, unmapped = set(), set(), set(), []
    for op in sorted(ops):
        ns, _, rest = op.partition("::")
        base = rest.split(".")[0]
        if ns == "cortex_m" and base in avail["Cortex-M"]:
            cortex_m.add(base)
        elif ns == "quantized_decomposed":
            comp = QUANTIZED_DECOMPOSED_TO_COMPONENT.get(base, base)
            if comp in avail["Quantized"]:
                quantized.add(comp)
            else:
                unmapped.append(op)
        elif ns == "aten":
            cand = base[:-5] if base.endswith("_copy") and base[:-5] in avail["Portable"] else base
            if cand in avail["Portable"]:
                portable.add(cand)
            else:
                unmapped.append(op)
        else:
            unmapped.append(op)
    return sorted(portable), sorted(quantized), sorted(cortex_m), unmapped


def render(portable, quantized, cortex_m, pack_name, pack_path, description) -> str:
    lines = [
        "# Generated by scripts/gen_components.py -- regenerate when the model's",
        "# operator set changes. This is the model's CMSIS component selection.",
        "layer:",
        "  type: AI",
        f"  description: {description}",
        "",
        "  packs:",
        f"    - pack: {pack_name}",
    ]
    if pack_path:
        lines.append(f"      path: {pack_path}")
    lines += [
        "",
        "  define:",
        "    - ET_LOG_ENABLED: 0",
        "",
        "  components:",
        "    # ExecuTorch core runtime (Runtime ships the weak bare-metal PAL).",
        "    - component: Machine Learning:ExecuTorch:Runtime",
        "    - component: Machine Learning:ExecuTorch:Kernel Utils",
        "    - component: Machine Learning:ExecuTorch:Kernel Registration",
        "    # Ethos-U NPU backend (the model is fully delegated to it).",
        "    - component: Machine Learning:ExecuTorch:Backend EthosU",
    ]
    if cortex_m:
        lines.append("    # Cortex-M (CMSIS-NN) boundary/quant operators.")
        lines += [f"    - component: Machine Learning:ExecuTorch Operators:Cortex-M {c}" for c in cortex_m]
    if quantized:
        lines.append("    # Quantized reference operators.")
        lines += [f"    - component: Machine Learning:ExecuTorch Operators:Quantized {c}" for c in quantized]
    if portable:
        lines.append("    # Portable operators executed on the CPU.")
        lines += [f"    - component: Machine Learning:ExecuTorch Operators:Portable {c}" for c in portable]
    return "\n".join(lines) + "\n"


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--pte", type=Path, required=True)
    p.add_argument("--pack-path", type=Path, required=True)
    p.add_argument("--pack-name", default="PyTorch::ExecuTorch")
    p.add_argument("--output", type=Path, required=True)
    p.add_argument("--description", default="AI layer for the TinyCNN Ethos-U85 example")
    p.add_argument("--layer-pack-path", help="pack path as written into the layer (default: relative to layer)")
    args = p.parse_args()

    pdsc = next(args.pack_path.glob("*.pdsc"))
    avail = pack_component_suffixes(pdsc)
    ops = extract_ops(args.pte)
    portable, quantized, cortex_m, unmapped = map_ops(ops, avail)

    layer_pack_path = args.layer_pack_path
    if layer_pack_path is None:
        # Path written into the layer is relative to the layer's own directory.
        import os
        layer_pack_path = os.path.relpath(args.pack_path.resolve(), args.output.resolve().parent)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        render(portable, quantized, cortex_m, args.pack_name, layer_pack_path, args.description)
    )
    print(f"[gen_components] {args.output}")
    print(f"  cortex-m: {cortex_m}")
    print(f"  quantized: {quantized}")
    print(f"  portable: {portable}")
    if unmapped:
        print(f"  [warn] unmapped ops (not in pack): {unmapped}")


if __name__ == "__main__":
    main()
