#!/usr/bin/env python3
"""
Generate a pack-based ai_layer.clayer.yml from model operator metadata.

This script translates ExecuTorch operator names (aten::, quantized_decomposed::)
into PyTorch::ExecuTorch CMSIS-Pack component references, producing a self-contained
clayer.yml that replaces the source-based stage1/stage2 layers.

Usage:
  # From a .pte model file (extracts operators via strings):
  python3 generate_pack_clayer.py --model model/ethos_u_minimal_example.pte -o ai_layer/ai_layer.clayer.yml

  # From an operators list file:
  python3 generate_pack_clayer.py --ops-file model/operators_minimal.txt -o ai_layer/ai_layer.clayer.yml

  # From a selected_operators.yaml (generated by ExecuTorch build):
  python3 generate_pack_clayer.py --selected-yaml out/stage2/assets/meta/selected_operators.yaml -o ai_layer/ai_layer.clayer.yml

  # With explicit pack path and model header:
  python3 generate_pack_clayer.py --ops-file model/operators_cnn.txt \
    --pack-path ../packs/PyTorch.ExecuTorch.1.1.0-rc1-build.12 \
    --model-header ai_layer/model/model_pte.h \
    --ethos-u --cortex-m \
    -o ai_layer/ai_layer.clayer.yml
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


# ──────────────────────────────────────────────────────────────────────────────
# Operator → Pack Component Mapping
# ──────────────────────────────────────────────────────────────────────────────

# All portable operator component names available in the pack (Csub values)
PORTABLE_COMPONENTS = {
    "abs", "acos", "acosh", "add", "addmm", "alias_copy", "allclose",
    "amax", "amin", "any", "arange", "argmax", "argmin", "as_strided_copy",
    "asin", "asinh", "atan", "atan2", "atanh", "avg_pool2d",
    "bitwise_and", "bitwise_left_shift", "bitwise_not", "bitwise_or",
    "bitwise_right_shift", "bitwise_xor", "bmm",
    "cat", "cdist_forward", "ceil", "clamp", "clone", "clone_dim_order",
    "constant_pad_nd", "convolution", "convolution_backward", "copy",
    "cos", "cosh", "cumsum",
    "detach_copy", "diagonal_copy", "div",
    "elu", "embedding", "empty", "empty_dim_order", "eq", "erf", "exp",
    "expand_copy", "expm1",
    "fill", "flip", "floor", "floor_divide", "fmod", "full", "full_like",
    "gather", "ge", "gelu", "glu", "grid_sampler_2d", "gt",
    "hardtanh",
    "index", "index_put", "index_select", "isinf", "isnan",
    "le", "leaky_relu", "lift_fresh_copy", "log", "log10", "log1p", "log2",
    "log_softmax", "logical_and", "logical_not", "logical_or", "logical_xor",
    "logit", "lt",
    "masked_fill", "masked_scatter", "masked_select", "max",
    "max_pool2d_with_indices", "max_pool2d_with_indices_backward",
    "maximum", "mean", "min", "minimum", "mm", "mul",
    "narrow_copy", "native_batch_norm", "native_dropout",
    "native_group_norm", "native_layer_norm", "ne", "neg", "nonzero",
    "ones",
    "pdist_forward", "permute_copy", "pixel_shuffle", "pixel_unshuffle",
    "pow", "prod",
    "rand", "randn", "reciprocal",
    "reflection_pad1d", "reflection_pad2d", "reflection_pad3d",
    "relu", "remainder", "repeat", "repeat_interleave",
    "replication_pad1d", "replication_pad2d", "replication_pad3d",
    "roll", "round", "rsqrt", "rsub",
    "scalar_tensor", "scatter", "scatter_add", "select_copy",
    "select_scatter", "sigmoid", "sign", "sin", "sinh",
    "slice_copy", "slice_scatter", "softmax",
    "split_copy", "split_with_sizes_copy", "sqrt", "squeeze_copy",
    "stack", "sub", "sum",
    "t_copy", "tan", "tanh", "to_copy", "to_dim_order_copy", "topk",
    "transpose_copy", "tril", "trunc",
    "unbind_copy", "unfold_copy", "unsqueeze_copy",
    "upsample_bilinear2d", "upsample_bilinear2d_aa", "upsample_nearest2d",
    "var", "view_as_real_copy", "view_copy", "where", "zeros",
}

# Quantized operator component names available in the pack
QUANTIZED_COMPONENTS = {
    "add", "choose_qparams", "dequantize", "embedding",
    "embedding2b", "embedding4b", "mixed_linear", "mixed_mm", "quantize",
}

# Special aten:: operator name → portable component name mappings
# Most aten ops map directly: aten::relu.out → relu
# These handle cases where the aten name differs from the component name
ATEN_TO_PORTABLE = {
    # Operators with leading underscores in aten:: names
    "_softmax": "softmax",
    "_log_softmax": "log_softmax",
    "_cdist_forward": "cdist_forward",
    "_pdist_forward": "pdist_forward",
    "_to_copy": "to_copy",
    "_native_batch_norm_legit": "native_batch_norm",
    "_native_batch_norm_legit_no_training": "native_batch_norm",
    # Alias mappings for common operator name variants
    "conv2d": "convolution",          # aten::conv2d.out → convolution component
    "linear": "addmm",               # aten::linear.out → addmm (linear decomposed)
    "batch_norm": "native_batch_norm",
    "layer_norm": "native_layer_norm",
    "group_norm": "native_group_norm",
    "dropout": "native_dropout",
    "adaptive_avg_pool2d": "avg_pool2d",  # fallback to avg_pool2d
}

# quantized_decomposed:: operator → quantized component mappings
# Many variants map to the same component
QUANTIZED_DECOMPOSED_TO_COMPONENT = {
    "quantize_per_tensor": "quantize",
    "quantize_per_channel": "quantize",
    "quantize_per_token": "quantize",
    "dequantize_per_tensor": "dequantize",
    "dequantize_per_channel": "dequantize",
    "dequantize_per_token": "dequantize",
    "add": "add",
    "choose_qparams": "choose_qparams",
    "embedding_byte": "embedding",
    "embedding_2bit": "embedding2b",
    "embedding_4bit": "embedding4b",
    "mixed_linear": "mixed_linear",
    "mixed_mm": "mixed_mm",
}


def resolve_portable_component(op_name: str) -> Optional[str]:
    """
    Resolve an aten:: operator name to a portable component name.
    
    Examples:
        "add" → "add"
        "relu" → "relu"  
        "_softmax" → "softmax"
        "conv2d" → "convolution"
        "softmax.int" → "softmax"
    """
    # Strip trailing .out, .Tensor_out, .int_out, .dim_out, etc.
    base = op_name.split(".")[0]
    
    # Check explicit mapping first
    if base in ATEN_TO_PORTABLE:
        component = ATEN_TO_PORTABLE[base]
        if component in PORTABLE_COMPONENTS:
            return component
    
    # Direct match
    if base in PORTABLE_COMPONENTS:
        return base
    
    # Try stripping leading underscore  
    if base.startswith("_") and base[1:] in PORTABLE_COMPONENTS:
        return base[1:]
    
    # Try stripping _copy suffix and matching
    if base.endswith("_copy"):
        without_copy = base[:-5]
        if without_copy in PORTABLE_COMPONENTS:
            return without_copy
    
    return None


def resolve_quantized_component(op_name: str) -> Optional[str]:
    """
    Resolve a quantized_decomposed:: operator name to a quantized component name.
    
    Examples:
        "quantize_per_tensor" → "quantize"
        "dequantize_per_channel" → "dequantize"
        "embedding_byte" → "embedding"
    """
    # Strip trailing .out, .Tensor_out, etc.
    base = op_name.split(".")[0]
    
    # Check explicit mapping
    if base in QUANTIZED_DECOMPOSED_TO_COMPONENT:
        component = QUANTIZED_DECOMPOSED_TO_COMPONENT[base]
        if component in QUANTIZED_COMPONENTS:
            return component
    
    # Direct match
    if base in QUANTIZED_COMPONENTS:
        return base
    
    return None


def parse_operators_file(path: Path) -> list[str]:
    """
    Parse an operators list file (one operator per line, # comments).
    Returns raw operator strings like "aten::add.out".
    """
    ops = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            ops.append(line)
    return ops


def parse_selected_operators_yaml(path: Path) -> list[str]:
    """
    Parse ExecuTorch's selected_operators.yaml to extract operator names.
    Format is typically:
        operators:
          aten::add.out:
            ...
          quantized_decomposed::quantize_per_tensor.out:
            ...
    """
    ops = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            # Match lines like "aten::add.out:" or "quantized_decomposed::dequantize_per_tensor.out:"
            if (line.startswith("aten::") or line.startswith("quantized_decomposed::")) and line.endswith(":"):
                ops.append(line.rstrip(":").strip())
    return ops


def extract_operators_from_pte(pte_path: Path) -> list[str]:
    """
    Extract operator names from a .pte model file using strings.
    Looks for aten:: and quantized_decomposed:: patterns.
    """
    try:
        result = subprocess.run(
            ["strings", str(pte_path)],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            print(f"[WARN] strings command failed on {pte_path}", file=sys.stderr)
            return []
    except Exception as e:
        print(f"[WARN] Failed to run strings on {pte_path}: {e}", file=sys.stderr)
        return []
    
    ops = set()
    for line in result.stdout.splitlines():
        line = line.strip()
        # Match full operator references
        for match in re.finditer(r'(aten::\w+(?:\.\w+)*)', line):
            ops.add(match.group(1))
        for match in re.finditer(r'(quantized_decomposed::\w+(?:\.\w+)*)', line):
            ops.add(match.group(1))
    
    return sorted(ops)


def translate_operators(raw_ops: list[str], verbose: bool = False) -> tuple[list[str], list[str], list[str]]:
    """
    Translate raw operator strings to pack component names.
    
    Returns:
        (portable_components, quantized_components, unmapped_operators)
    """
    portable = set()
    quantized = set()
    unmapped = []
    
    for op in raw_ops:
        if op.startswith("aten::"):
            op_name = op[len("aten::"):]
            component = resolve_portable_component(op_name)
            if component:
                portable.add(component)
                if verbose:
                    print(f"  {op} → Operators Portable {component}")
            else:
                unmapped.append(op)
                if verbose:
                    print(f"  {op} → [UNMAPPED]")
        
        elif op.startswith("quantized_decomposed::"):
            op_name = op[len("quantized_decomposed::"):]
            component = resolve_quantized_component(op_name)
            if component:
                quantized.add(component)
                if verbose:
                    print(f"  {op} → Operators Quantized {component}")
            else:
                unmapped.append(op)
                if verbose:
                    print(f"  {op} → [UNMAPPED]")
        
        else:
            # Unknown namespace — try as portable
            component = resolve_portable_component(op)
            if component:
                portable.add(component)
                if verbose:
                    print(f"  {op} → Operators Portable {component} (inferred)")
            else:
                unmapped.append(op)
                if verbose:
                    print(f"  {op} → [UNMAPPED]")
    
    return sorted(portable), sorted(quantized), unmapped


def generate_clayer_yml(
    portable_components: list[str],
    quantized_components: list[str],
    pack_name: str = "PyTorch::ExecuTorch",
    pack_path: Optional[str] = None,
    description: str = "AI layer using PyTorch ExecuTorch pack",
    model_header: Optional[str] = None,
    report_file: Optional[str] = None,
    ethos_u: bool = True,
    cortex_m: bool = False,
    bare_metal: bool = True,
    random_stubs: bool = True,
    log_enabled: int = 0,
) -> str:
    """Generate the YAML content for a pack-based ai_layer.clayer.yml."""
    
    lines = []
    lines.append("layer:")
    lines.append("  type: AI")
    lines.append(f"  description: {description}")
    lines.append("")
    lines.append("  packs:")
    
    if pack_path:
        lines.append(f"    - pack: {pack_name}")
        lines.append(f"      path: {pack_path}")
    else:
        lines.append(f"    - pack: {pack_name}")
    
    lines.append("")
    
    # Defines
    lines.append("  define:")
    lines.append(f"    - ET_LOG_ENABLED : {log_enabled}")
    lines.append("")
    
    # Components
    lines.append("  components:")
    lines.append("    # ExecuTorch core runtime")
    lines.append("    - component: Machine Learning:ExecuTorch:Runtime")
    lines.append("    - component: Machine Learning:ExecuTorch:Kernel Utils")
    lines.append("    - component: Machine Learning:ExecuTorch:Kernel Registration")
    
    # Backends
    if ethos_u:
        lines.append("    # Ethos-U NPU backend")
        lines.append("    - component: Machine Learning:ExecuTorch:Backend EthosU")
    if cortex_m:
        lines.append("    # CMSIS-NN Cortex-M backend")
        lines.append("    - component: Machine Learning:ExecuTorch:Backend CortexM")
    
    # Platform stubs
    if bare_metal:
        lines.append("    # Bare-metal PAL stubs (replaces posix.cpp)")
        lines.append("    - component: Machine Learning:ExecuTorch:Platform Bare-Metal")
    if random_stubs:
        lines.append("    # Random op stubs (no std::random_device on bare-metal)")
        lines.append("    - component: Machine Learning:ExecuTorch:Stubs RandomOps")
    
    # Operator components
    if portable_components:
        lines.append("    # Portable operators used by the model")
        for comp in portable_components:
            lines.append(f"    - component: Machine Learning:ExecuTorch:Operators Portable {comp}")
    
    if quantized_components:
        lines.append("    # Quantized operators used by the model")
        for comp in quantized_components:
            lines.append(f"    - component: Machine Learning:ExecuTorch:Operators Quantized {comp}")
    
    # Model files group
    model_files = []
    if model_header:
        model_files.append(model_header)
    if report_file:
        model_files.append(report_file)
    
    if model_files:
        lines.append("")
        lines.append("  groups:")
        lines.append("    # AI Model")
        lines.append("    - group: Executorch Model")
        lines.append("      files:")
        for f in model_files:
            lines.append(f"        - file: {f}")
    
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a pack-based ai_layer.clayer.yml from model operators",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    
    # Input sources (at least one required)
    input_group = parser.add_argument_group("Operator input (at least one required)")
    input_group.add_argument(
        "--model", "-m",
        help="Path to .pte model file (extracts operators via strings)",
    )
    input_group.add_argument(
        "--ops-file", "-f",
        help="Path to operators list file (one per line, # comments)",
    )
    input_group.add_argument(
        "--selected-yaml", "-y",
        help="Path to selected_operators.yaml from ExecuTorch build",
    )
    input_group.add_argument(
        "--ops", "-O",
        help="Comma-separated operator list (e.g. 'aten::add.out,aten::relu.out')",
    )
    
    # Pack configuration
    pack_group = parser.add_argument_group("Pack configuration")
    pack_group.add_argument(
        "--pack-name",
        default="PyTorch::ExecuTorch",
        help="CMSIS pack name (default: PyTorch::ExecuTorch)",
    )
    pack_group.add_argument(
        "--pack-path",
        help="Relative path to the pack directory (optional, for local packs)",
    )
    
    # Backend options
    backend_group = parser.add_argument_group("Backend options")
    backend_group.add_argument(
        "--ethos-u", action="store_true", default=True,
        help="Include Ethos-U NPU backend (default: true)",
    )
    backend_group.add_argument(
        "--no-ethos-u", action="store_true",
        help="Exclude Ethos-U NPU backend",
    )
    backend_group.add_argument(
        "--cortex-m", action="store_true",
        help="Include CMSIS-NN Cortex-M backend",
    )
    backend_group.add_argument(
        "--no-bare-metal", action="store_true",
        help="Exclude bare-metal platform stubs",
    )
    backend_group.add_argument(
        "--no-random-stubs", action="store_true",
        help="Exclude random ops stubs",
    )
    
    # Model files
    model_group = parser.add_argument_group("Model files")
    model_group.add_argument(
        "--model-header",
        help="Path to model_pte.h (relative to layer, e.g. ./model/model_pte.h)",
    )
    model_group.add_argument(
        "--report",
        help="Path to REPORT.md (relative to layer, e.g. ./model/REPORT.md)",
    )
    
    # Output
    parser.add_argument(
        "--output", "-o",
        required=True,
        help="Output path for the generated clayer.yml",
    )
    parser.add_argument(
        "--description", "-d",
        default="AI layer using PyTorch ExecuTorch pack",
        help="Layer description",
    )
    parser.add_argument(
        "--log-enabled", type=int, default=0,
        help="Value for ET_LOG_ENABLED define (default: 0)",
    )
    parser.add_argument("--verbose", "-v", action="store_true")
    parser.add_argument("--dry-run", action="store_true", help="Print YAML to stdout without writing file")
    
    args = parser.parse_args()
    
    # Collect operators from all sources
    raw_ops = []
    
    if args.ops:
        raw_ops.extend(args.ops.split(","))
        if args.verbose:
            print(f"[INFO] Loaded {len(args.ops.split(','))} operators from command line")
    
    if args.ops_file:
        path = Path(args.ops_file)
        if not path.exists():
            print(f"[ERROR] Operators file not found: {path}", file=sys.stderr)
            sys.exit(1)
        file_ops = parse_operators_file(path)
        raw_ops.extend(file_ops)
        if args.verbose:
            print(f"[INFO] Loaded {len(file_ops)} operators from {path}")
    
    if args.selected_yaml:
        path = Path(args.selected_yaml)
        if not path.exists():
            print(f"[ERROR] Selected operators YAML not found: {path}", file=sys.stderr)
            sys.exit(1)
        yaml_ops = parse_selected_operators_yaml(path)
        raw_ops.extend(yaml_ops)
        if args.verbose:
            print(f"[INFO] Loaded {len(yaml_ops)} operators from {path}")
    
    if args.model:
        path = Path(args.model)
        if not path.exists():
            print(f"[ERROR] Model file not found: {path}", file=sys.stderr)
            sys.exit(1)
        pte_ops = extract_operators_from_pte(path)
        raw_ops.extend(pte_ops)
        if args.verbose:
            print(f"[INFO] Extracted {len(pte_ops)} operators from {path}")
    
    if not raw_ops:
        print("[ERROR] No operators provided. Use --model, --ops-file, --selected-yaml, or --ops", file=sys.stderr)
        sys.exit(1)
    
    # Deduplicate
    raw_ops = sorted(set(raw_ops))
    
    if args.verbose:
        print(f"\n[INFO] Total unique operators: {len(raw_ops)}")
        print("[INFO] Translating operators to pack components...")
    
    # Translate to pack components
    portable, quantized, unmapped = translate_operators(raw_ops, verbose=args.verbose)
    
    if args.verbose:
        print(f"\n[INFO] Portable components: {len(portable)}")
        print(f"[INFO] Quantized components: {len(quantized)}")
        if unmapped:
            print(f"[WARN] Unmapped operators ({len(unmapped)}):")
            for op in unmapped:
                print(f"  - {op}")
    
    if unmapped:
        print(f"[WARN] {len(unmapped)} operator(s) could not be mapped to pack components:", file=sys.stderr)
        for op in unmapped:
            print(f"  {op}", file=sys.stderr)
    
    # Generate YAML
    ethos_u = args.ethos_u and not args.no_ethos_u
    bare_metal = not args.no_bare_metal
    random_stubs = not args.no_random_stubs
    
    yaml_content = generate_clayer_yml(
        portable_components=portable,
        quantized_components=quantized,
        pack_name=args.pack_name,
        pack_path=args.pack_path,
        description=args.description,
        model_header=args.model_header,
        report_file=args.report,
        ethos_u=ethos_u,
        cortex_m=args.cortex_m,
        bare_metal=bare_metal,
        random_stubs=random_stubs,
        log_enabled=args.log_enabled,
    )
    
    if args.dry_run:
        print(yaml_content)
    else:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(yaml_content)
        print(f"[OK] Generated {output_path}")
        print(f"     {len(portable)} portable + {len(quantized)} quantized operator components")
        if unmapped:
            print(f"     {len(unmapped)} operators could not be mapped (see warnings above)")


if __name__ == "__main__":
    main()
