// Generated by create_ai_layer.py -- do not edit.
#pragma once

// Run-time memory of the program: its memory-planned tensors, and the scratch
// the Ethos-U backend takes from the temp allocator for an inference.
#define MODEL_PTE_PLANNED_SIZE 3840
#define MODEL_PTE_SCRATCH_SIZE 8192

#ifdef __cplusplus
extern "C" {
#endif
extern const unsigned char model_pte[];
extern const unsigned long model_pte_size;
#ifdef __cplusplus
}
#endif
